### ISSUE TITLE
About shortcodes, maybe a bug?

### ISSUE THREAD

**Issue by jcold** [kivikakk/comrak#340]
I found some shortcodes cant not recognize, e.g.  `:-1:`  `:+1:` , but emojis work fine. 

// Cargo.toml

```toml
[package]
name = "emoji"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = { version = "0.18.0", features = ["emojis", "shortcodes"] }
emojis = "0.5"

```

// main.rs

```rust
use comrak::{markdown_to_html, ComrakOptions};

fn main() {
    let rocket = emojis::get_by_shortcode("+1").unwrap();
    assert_eq!("👍", rocket.as_str());

    let mut opts = ComrakOptions::default();
    opts.extension.shortcodes = true;

    assert_eq!(
        markdown_to_html(":-1: :+1: :question:", &opts),
        "👎 👍 ❓"
    );

    println!("Hello, world! {}", rocket);
}
```
